class companyName:
    company_tickers = {
    "Apple Inc.": "AAPL",
    "Microsoft Corporation": "MSFT",
    "Amazon.com Inc.": "AMZN",
    "Alphabet Inc. Class A": "GOOGL",
    "Alphabet Inc. Class C": "GOOG",
    "NVIDIA Corporation": "NVDA",
    "Meta Platforms Inc.": "META",
    "Tesla Inc.": "TSLA",
    "Berkshire Hathaway Class B": "BRK-B",
    "JPMorgan Chase & Co.": "JPM",
    "Johnson & Johnson": "JNJ",
    "Visa Inc.": "V",
    "Mastercard Incorporated": "MA",
    "Walmart Inc.": "WMT",
    "Procter & Gamble Co.": "PG",
    "Home Depot Inc.": "HD",
    "Netflix Inc.": "NFLX",
    "Disney (Walt) Co.": "DIS",
    "PayPal Holdings Inc.": "PYPL",
    "Intel Corporation": "INTC",
    "Cisco Systems Inc.": "CSCO",
    "Oracle Corporation": "ORCL",
    "Adobe Inc.": "ADBE",
    "Salesforce Inc.": "CRM",
    "Qualcomm Incorporated": "QCOM",
    "AMD (Advanced Micro Devices)": "AMD",
    "AT&T Inc.": "T",
    "Verizon Communications": "VZ",
    "Exxon Mobil Corporation": "XOM",
    "Chevron Corporation": "CVX",
    "Pfizer Inc.": "PFE",
    "Merck & Co. Inc.": "MRK",
    "AbbVie Inc.": "ABBV",
    "Coca-Cola Company": "KO",
    "PepsiCo Inc.": "PEP",
    "McDonald's Corporation": "MCD",
    "Starbucks Corporation": "SBUX",
    "Boeing Company": "BA",
    "Ford Motor Company": "F",
    "General Motors": "GM",
    "Uber Technologies Inc.": "UBER",
    "Lyft Inc.": "LYFT",
    "Domino's Pizza Inc.": "DPZ",
    "3M Company": "MMM",
    "BlackRock Inc.": "BLK",
    "Uber Technologies Inc.": "UBER",
    "Airbnb Inc.": "ABNB",
    "Snowflake Inc.": "SNOW",
    "Shopify Inc.": "SHOP",
    "Block Inc. (Square)": "SQ",
    "Coinbase Global Inc.": "COIN",
    "Spotify Technology": "SPOT",
    "Robinhood Markets": "HOOD",
    "Rivian Automotive Inc.": "RIVN",
    "Lucid Group Inc.": "LCID",
    "Dell Technologies": "DELL",
    "IBM Corporation": "IBM",
    "HP Inc.": "HPQ",
    "Zoom Video Communications": "ZM",
    "American Express Company": "AXP",
    "Bank of America": "BAC",
    "Wells Fargo & Co.": "WFC",
    "Goldman Sachs": "GS",
    "Morgan Stanley": "MS",
    "Charles Schwab Corporation": "SCHW",
    "FedEx Corporation": "FDX",
    "United Parcel Service (UPS)": "UPS",
    "Caterpillar Inc.": "CAT",
    "Deere & Company": "DE",
    "Lockheed Martin Corporation": "LMT",
    "Raytheon Technologies": "RTX",
    "General Electric": "GE",
    "Siemens": "SIE.DE",
    "Volkswagen AG": "VOW.DE",
    "Toyota Motor Corp.": "TM",
    "Samsung Electronics": "005930.KS",
    "Sony Group Corp.": "SONY",
    "Tencent Holdings": "0700.HK",
    "Alibaba Group": "BABA",
    "BYD Company": "1211.HK",
    "TSMC (Taiwan Semiconductor)": "TSM",
    "ASML Holding": "ASML",
    "SAP SE": "SAP",
    "Nestle SA": "NESN.SW",
    "Novartis": "NOVN.SW",
    "HSBC Holdings": "HSBA.L",
    "BP PLC": "BP.L",
    "Shell PLC": "SHEL.L",
    "AstraZeneca": "AZN",
    "Unilever PLC": "UL",
    "L'Oréal": "OR.PA",
    "Louis Vuitton (LVMH)": "MC.PA",
    "Volkswagen AG Pref": "VOW3.DE",
    "Banco Santander": "SAN",
    "ING Group": "ING",
    "Roche Holding AG": "ROG.SW"
}


