class companyName:
    company_tickers = {
        "Apple Inc.": "AAPL",
        "Microsoft Corporation": "MSFT",
        "Amazon.com, Inc.": "AMZN",
        "Alphabet Inc. (Class A)": "GOOGL",
        "Alphabet Inc. (Class C)": "GOOG",
        "Berkshire Hathaway Inc. (Class B)": "BRK.B",
        "Tesla, Inc.": "TSLA",
        "JPMorgan Chase & Co.": "JPM",
        "Johnson & Johnson": "JNJ",
        "Visa Inc. (Class A)": "V",
        "Walmart Inc.": "WMT",
        "Procter & Gamble Company": "PG",
        "Exxon Mobil Corporation": "XOM",
        "Meta Platforms, Inc.": "META",
        "Intel Corporation": "INTC",
        "The Coca-Cola Company": "KO",
        "PepsiCo, Inc.": "PEP",
        "Pfizer Inc.": "PFE",
        "Chevron Corporation": "CVX",
        "Netflix, Inc.": "NFLX",
        "Adobe Inc.": "ADBE",
        "Salesforce, Inc.": "CRM",
        "International Business Machines Corporation": "IBM",
        "The Walt Disney Company": "DIS",
        "McDonald’s Corporation": "MCD",
        "Nike, Inc.": "NKE",
        "Cisco Systems, Inc.": "CSCO",
        "Oracle Corporation": "ORCL",
        "AbbVie Inc.": "ABBV",
        "Merck & Co., Inc.": "MRK",
        # Indian companies (NSE/ BSE) example:
        "Reliance Industries Ltd.": "RELIANCE",
        "HDFC Bank Ltd.": "HDFCBANK",
        "Infosys Ltd.": "INFY",
        "ICICI Bank Ltd.": "ICICIBANK",
        "Tata Consultancy Services Ltd.": "TCS",
        "Hindustan Unilever Ltd.": "HINDUNILVR",
        "Bharti Airtel Ltd.": "BHARTIARTL",
        "State Bank of India": "SBIN",
        "ITC Ltd.": "ITC",
        "Larsen & Toubro Ltd.": "LT",
    }
